# Generated by Django 4.2.4 on 2023-08-22 17:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombreperfil', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='nombrePerfil', max_length=10)),
            ],
            options={
                'db_table': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Psicosis',
            fields=[
                ('idpsicosis', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta21', models.BooleanField()),
                ('pregunta22', models.BooleanField()),
                ('pregunta23', models.BooleanField()),
                ('pregunta24', models.BooleanField()),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psicosis',
            },
        ),
        migrations.CreateModel(
            name='Epilepsia',
            fields=[
                ('idepilepsia', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta25', models.BooleanField()),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Epilepsia',
            },
        ),
        migrations.CreateModel(
            name='Datospersonales',
            fields=[
                ('iddatospersonales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('sexo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('estadocivil', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('fechanacimiento', models.DateField()),
                ('codigo', models.IntegerField()),
                ('gradoinstruccion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('ocupacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('anodeingreso', models.IntegerField()),
                ('direccionactual', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('numerocel', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=15)),
                ('vivecon', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('numerohermanos', models.IntegerField()),
                ('familiarresponsable', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('numerocelresponsable', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=15)),
                ('religion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('beneficios', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('escuela', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('facultad', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datospersonales',
            },
        ),
        migrations.CreateModel(
            name='Ansiedad',
            fields=[
                ('idansiedad', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta1', models.BooleanField()),
                ('pregunta2', models.BooleanField()),
                ('pregunta3', models.BooleanField()),
                ('pregunta4', models.BooleanField()),
                ('pregunta5', models.BooleanField()),
                ('pregunta6', models.BooleanField()),
                ('pregunta7', models.BooleanField()),
                ('pregunta8', models.BooleanField()),
                ('pregunta9', models.BooleanField()),
                ('pregunta10', models.BooleanField()),
                ('pregunta11', models.BooleanField()),
                ('pregunta12', models.BooleanField()),
                ('pregunta13', models.BooleanField()),
                ('pregunta14', models.BooleanField()),
                ('pregunta15', models.BooleanField()),
                ('pregunta16', models.BooleanField()),
                ('pregunta17', models.BooleanField()),
                ('pregunta18', models.BooleanField()),
                ('pregunta19', models.BooleanField()),
                ('pregunta20', models.BooleanField()),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ansiedad',
            },
        ),
        migrations.CreateModel(
            name='Alcoholismo',
            fields=[
                ('idalcoholismo', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta26', models.BooleanField()),
                ('pregunta27', models.BooleanField()),
                ('pregunta28', models.BooleanField()),
                ('pregunta29', models.BooleanField()),
                ('pregunta30', models.BooleanField()),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alcoholismo',
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='aplication.perfiles'),
        ),
    ]
